---
apt_prior_packages:
- apt-transport-https
- curl
- software-properties-common

apt_keys:
- https://dl-ssl.google.com/linux/linux_signing_key.pub

gpg_armor_keys:
- url: https://download.sublimetext.com/sublimehq-pub.gpg
  filename: sublimehq-archive.gpg
  target_dir: /etc/apt/trusted.gpg.d

apt_repositories:
- repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
  filename: google-chrome
- repo: deb https://download.sublimetext.com/ apt/stable/
  filename: sublime-text

apt_ppa:
- ppa:ansible/ansible

apt_packages:
- gawk
- flatpak
- gnome-software-plugin-flatpak
- sublime-text
- google-chrome-stable
- ansible
- httpie
- qbittorrent
- openjdk-21-jdk
- openjdk-21-source
- cuetools
- shntool
- flac
- ffmpeg
- rename
- wine
- plocate
- rar
- unrar
- p7zip-full
- p7zip-rar
- gmtp
- mc
- imagemagick
- docker.io
- podman
- tree
- guvcview
- cockpit
- virtualbox
- postgresql
- gnome-shell-extension-manager
- gir1.2-gtop-2.0
- lm-sensors
- vsftpd
- mpd
- cantata
- clementine
- mpc
- jackd2
- qsynth
- prometheus
- prometheus-alertmanager
- grafana
- htop

deb_packages:
- https://deac-fra.dl.sourceforge.net/project/deadbeef/travis/linux/1.10.0/deadbeef-static_1.10.0-1_amd64.deb
- https://github.com/kubernetes/minikube/releases/download/v1.35.0/minikube_1.35.0-0_amd64.deb

packages_distr_dir: /opt/distr

arhive_packages_install_dir: /opt

arhive_packages:
- url: https://gpumagick.com/downloads/files/2025/fm2/FurMark_2.7.0.0_linux64.7z
  name: furmark
- url: https://td.telegram.org/tlinux/tsetup.5.13.1.tar.xz
  name: telegram
- url: https://github.com/EuFlo/sacd-ripper/releases/download/0.3.9.3/sacd_extract-0.3.9.3-117-linux.zip
  name: sacd_extract

snap_packages:
- name: vlc
  classic: false
- name: foobar2000
  classic: false
- name: postman
  classic: false
- name: dbeaver-ce
  classic: false
- name: intellij-idea-community
  classic: true
- name: code
  classic: true
- name: kate
  classic: true
- name: go
  classic: true
- name: kate
  classic: true
- name: helm
  classic: true
- name: kubectl
  classic: true
- name: terraform
  classic: true

flatpak_repositories:
- name: flathub
  url: https://dl.flathub.org/repo/flathub.flatpakrepo

flatpak_packages:
- com.calibre_ebook.calibre
- org.filezillaproject.Filezilla
- org.gimp.GIMP
- org.audacityteam.Audacity

config_files:
- name: mpd.conf.j2
  path: /etc/mpd.conf
  service: mpd
- name: vsftpd.conf.j2
  path: /etc/vsftpd.conf
  service: vsftpd

shell_scripts:
- mpc update

local_bin:
- vagrant_2.4.3_linux_amd64/vagrant

username: dima
homedir_path: "/home/{{ username }}"
bashrc_path: "{{ homedir_path }}/.bashrc"
scripts_path: "{{ homedir_path }}/bin"
user_systemd_path: "{{ homedir_path }}/.config/systemd/user"

mpd:
  music_directory: /media/dima/WDC16Tb/Music
  audio_output:
  - name: "Shanling H7"
    device: "hw:CARD=H7,DEV=0"
  - name: "FIIO KA17"
    device: "hw:CARD=KA17,DEV=0"
  - name: "aune Flamingo DAC"
    device: "hw:CARD=DAC,DEV=0"
  user: null

vsftpd:
  write_enable: "YES"
  local_root: "/"
