#!/bin/bash

nautilus &>/dev/null /media/dima/Archive1/DSD/DSD &
sleep 1
nautilus &>/dev/null /media/dima/Archive1/PCM/PCM24 &
sleep 1
nautilus &>/dev/null /media/dima/Archive1/Scripts &
sleep 1
nautilus &>/dev/null /media/dima/Archive1/DSD/SACDc &
sleep 1
nautilus &>/dev/null /media/dima/Archive1/PCM/PCM16 &
sleep 1
nautilus &>/dev/null /media/dima/Archive2/MusicArchive &
sleep 1
nautilus &>/dev/null /media/dima/WDC1Tb/Downloads &
sleep 1
nautilus &>/dev/null /home/dima/Downloads &
sleep 1
nautilus &>/dev/null /home/dima/BooksIT/ru &
sleep 1